export default {
  TOKEN: {
    ACCESS_TOKEN: 'TOKEN_ACCESS_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'TOKEN_ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN: 'TOKEN_REFRESH_TOKEN',
    REFRESH_TOKEN_EXPIRED: 'TOKEN_REFRESH_TOKEN_EXPIRED'
  },
  TOAST_TIMEOUT: {
    ERROR: 3000,
    WARN: 3000,
    INFO: 2500,
    SUCCESS: 1500
  },
  APP: {
    CURRENT_LOCALE: 'user-locale'
  }
}
