export default {
  TOKEN: {
    ACCESS_TOKEN: 'TOKEN_ACCESS_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'TOKEN_ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN: 'TOKEN_REFRESH_TOKEN',
    REFRESH_TOKEN_EXPIRED: 'TOKEN_REFRESH_TOKEN_EXPIRED'
  },
  TOAST_TIMEOUT: {
    ERROR: 3500,
    WARN: 3500,
    INFO: 3000,
    SUCCESS: 2000
  },
  APP: {
    LANGUAGE: 'user-language'
  }
}
