export default {
  TOKEN: {
    ACCESS_TOKEN: 'TOKEN_ACCESS_TOKEN',
    ACCESS_TOKEN_EXPIRED: 'TOKEN_ACCESS_TOKEN_EXPIRED',
    AUTHORITIES: 'TOKEN_AUTHORITIES'
  },
  TOAST_TIMEOUT: {
    ERROR: 3000,
    WARN: 3000,
    INFO: 2500,
    SUCCESS: 1500
  },
  APP: {
    CURRENT_LOCALE: 'USER_LOCALE',
    SIGNIN_STATE: 'USER_SIGNIN_STATE'
  }
}
